language: node_js
node_js:
- stable
- lts/*
before_install:
- openssl aes-256-cbc -K $encrypted_9a7e1a4644f4_key -iv $encrypted_9a7e1a4644f4_iv
  -in .google-credentials.json.enc -out .google-credentials.json -d
env:
- GOOGLE_APPLICATION_CREDENTIALS=.google-credentials.json
